spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whatToEat?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true